name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v6
    - name: Use Node.js 20
      uses: actions/setup-node@v6
      with:
        node-version: 24
=======
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
>>>>>>> d7f89f1 (Initial commit)
    - run: npm ci
    - run: npm run lint
